### ISSUE TITLE
network airflow-kafka declared as external, but could not be found

### ISSUE THREAD

**Issue by DanielAdif** [dogukannulu/kafka_spark_structured_streaming#3]
Hi, I recently stumbled upon your repo when I was learning about streaming data, I tried to follow step by steps carefully but I encountered an error when running 
docker-compose -f docker-compose-LocalExecutor.yml up -d

Are there any prerequisites in order to follow the steps

![image](https://github.com/dogukannulu/kafka_spark_structured_streaming/assets/65440442/eaa85288-1714-4e98-b63b-16fa709985a2)

**Comment by dogukannulu** [comment]
Hey Daniel,

Could you please run `docker network create airflow-kafka`

**Comment by DanielAdif** [comment]
Okay, it's working now, I can follow through. Thank you :)
